name: Keep Alive

on:
  schedule:
    - cron: "0 0 1 * *" # Runs once a month

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent GitHub from disabling ALL workflows
        uses: liskin/gh-workflow-keepalive@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # List the exact filenames of the other workflows you want to save
          workflow_files: "validate.yaml,keep_alive.yaml"
